title: Caml Shaving
email: lambdasnow@gmail.com
description: Going Down The Rabbit Hole
author: sangwoo-joh
url: https://sangwoo-joh.github.io

# Social Profiles
github_username: sangwoo-joh
linkedin_username: sangwoo-joh

# Add your google-analytics ID here to activate google analytics
google_analytics: UA-145416085-1
disqus: blog-utrcmpd2xa

permalink: /:title

remote_theme: riggraz/no-style-please
theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
