title: Caml Shaving
email: work.sangwoo.joh@gmail.com
description: Going Down The Rabbit Hole
author: sangwoo-joh
url: https://sangwoo-joh.github.io

# Social Profiles
github_username: sangwoo-joh
linkedin_username: sangwoo-joh

# Add your google-analytics ID here to activate google analytics
google_analytics: G-J0C68FHJ6L

permalink: /:title

# remote_theme: riggraz/no-style-please
theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: "/home/caml-shaving" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
